---
apiVersion: metacontroller.k8s.io/v1alpha1
kind: CompositeController
metadata:
  name: microredis-controller
spec:
  generateSelector: true
  parentResource:
    apiVersion: microredis.com/v1
    resource: redises
  childResources:
    - apiVersion: v1
      resource: pods
    - apiVersion: v1
      resource: persistentvolumeclaims
    - apiVersion: v1
      resource: services
      updateStrategy:
        method: InPlace
  hooks:
    sync:
      webhook:
        url: http://operator.default/sync
